#+title: ox-md-title: Document titles for ox-md.el
#+author: Jeff Kreeftmeijer
#+date: 2023-03-10
#+options: toc:nil

[[https://github.com/jeffkreeftmeijer/ox-md-title.el][Ox-md-title.el]] adds document titles to markdown files generated with ox-md and derivatives.


Ox-md-title is disabled by default, even after requiring and enabling the library.
It only adds titles to Markdown export when =org-md-title= is non-nil:

#+name: option
#+begin_src emacs-lisp
  (defgroup org-export-md-title nil
    "Options for org-md-title."
    :tag "Org Markdown Title"
    :group 'org-export
    :version "24.4"
    :package-version '(Org . "8.0"))

  (defcustom org-md-title nil
    "Non-nil means to include the title in the exported document."
    :group 'org-export-md-title
    :version "24.4"
    :package-version '(Org . "8.0")
    :type 'boolean)
#+end_src

The package works by advising two functions.
First, it advises =org-md-template= by prepending the document title.
The title is built by calling out to =org-md--headline-title=[fn:org-md-headline] with the headline style and title extracted from the =info= variable:

#+name: template
#+begin_src emacs-lisp
  (defun org-md-title--advise-template (orig-fun &rest args)
    (concat
     (when org-md-title
       (let* ((info (nth 1 args))
	      (style (plist-get info :md-headline-style))
	      (title (org-export-data (plist-get info :title) info)))
	 (org-md--headline-title style 0 title nil)))
     (apply orig-fun args)))
#+end_src

Because a new title is prepended to the document, any already-existing headlines need their levels bumped up.
The second advice intercepts calls to =org-md--headline-title= and increments the second parameter before calling the original function:

#+name: headline
#+begin_src emacs-lisp
  (defun org-md-title--advise-headline (args)
    (when org-md-title
      (setf (nth 1 args) (+ (nth 1 args) 1)))
    args)
#+end_src

Finally, the added functions are added as advice:

#+name: advice
#+begin_src emacs-lisp
  (defun org-md-title-add ()
    (advice-add 'org-md--headline-title :filter-args #'org-md-title--advise-headline)
    (advice-add 'org-md-template :around #'org-md-title--advise-template))

  (defun org-md-title-remove ()
    (advice-remove 'org-md--headline-title #'org-md-title--advise-headline)
    (advice-remove 'org-md-template #'org-md-title--advise-template))
#+end_src

#+headers: :tangle ox-md-title.el
#+headers: :noweb yes
#+headers: :exports none
#+begin_src emacs-lisp
  ;;; ox-md-title.el --- Document titles for ox-md.el

  ;;; Commentary:

  ;; ox-md-title.el adds document titles to markdown files generated
  ;; with ox-md and derivatives.

  ;;; Code:

  (require 'ox-md)

  <<option>>

  <<template>>

  <<headline>>

  <<advice>>

  (provide 'ox-md-title)

  ;;; ox-md-title.el ends here
#+end_src

* Usage

Ox-md-title is currently not available through any of the package registries.
Instead, install it from the repository direcly.
Install the package with [[https://github.com/jwiegley/use-package][use-package]] and [[https://github.com/radian-software/straight.el][straight.el]], and enable it by calling =org-md-title-add=:

#+begin_src emacs-lisp
  (use-package ox-md-title
    :straight
    (ox-md-title :type git :host github :repo "jeffkreeftmeijer/ox-md-title.el")
    :config
    (org-md-title-add))
#+end_src

Alternatively, download =ox-md-title.el= and require it manually:

#+begin_src emacs-lisp
  (require 'ox-md-title)
  (org-md-title-add)
#+end_src

After calling =org-md-title-add=, set thte =org-md-title= variable to add document titles when exporting with ox-md:

#+begin_src emacs-lisp
  (let ((org-md-title t))
    (org-markdown-export-to-markdown))
#+end_src

[fn:org-md-headline] This package advises the private =org-md--headline-title= instead of =org-md-headline=, because the latter requires an actual Org headline element, which does not exist.
